/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { SmallestTTSOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Smallest.ai Waves text-to-speech adapter implementing `voice/tts` for `@absolutejs/voice` — lightning-fast streamed speech.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/smallest",
    name: "@absolutejs/voice-smallest",
    tagline: "Give your voice assistant a Smallest.ai voice.",
  },
  implements: [
    defineImplementation<SmallestTTSOptions>()({
      contract: "voice/tts",
      factory: "smallest",
      from: "@absolutejs/voice-smallest",
      requires: {
        env: [
          {
            description: "Smallest.ai API key",
            docsUrl: "https://waves.smallest.ai",
            key: "SMALLEST_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        voiceId: Type.String({
          description:
            "Voice id from the Waves voice library that speaks the assistant’s replies.",
          examples: ["emily"],
          title: "Voice",
        }),
        model: Type.Optional(
          Type.String({
            description: "Which Waves model generates the speech.",
            examples: ["lightning-v2"],
            title: "Speech model",
          }),
        ),
        language: Type.Optional(
          Type.String({
            description: "Language the assistant speaks.",
            examples: ["en"],
            title: "Spoken language",
          }),
        ),
      }),
      title: "Smallest.ai text-to-speech",
      wiring: {
        code: "smallest({ apiKey: ${env.SMALLEST_API_KEY} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-smallest", names: ["smallest"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
