/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from '@absolutejs/manifest';
import { Type } from '@sinclair/typebox';
import type { GoogleSpeechSTTOptions } from './types';

export const manifest = defineManifest<Record<never, never>>()({
	contract: 1,
	identity: {
		category: 'voice',
		description:
			'Google Cloud Speech-to-Text adapters implementing `voice/stt` for `@absolutejs/voice`: `googleSpeech` (buffered REST, simplest auth) wired here, plus `googleSpeechStream` (gRPC streaming partials, token auth) for real-time transcripts.',
		docsUrl: 'https://github.com/absolutejs/voice-adapters/tree/main/google-speech',
		name: '@absolutejs/voice-google-speech',
		tagline: 'Turn callers’ speech into text with Google Cloud.'
	},
	implements: [
		defineImplementation<GoogleSpeechSTTOptions>()({
			contract: 'voice/stt',
			factory: 'googleSpeech',
			from: '@absolutejs/voice-google-speech',
			requires: {
				env: [
					{
						description: 'Google Cloud API key with Speech-to-Text enabled',
						docsUrl: 'https://console.cloud.google.com/apis/credentials',
						key: 'GOOGLE_SPEECH_API_KEY',
						secret: true
					}
				]
			},
			settings: Type.Object({
				language: Type.Optional(
					Type.String({
						description: 'Language callers are expected to speak.',
						examples: ['en-US'],
						title: 'Spoken language'
					})
				),
				model: Type.Optional(
					Type.String({
						description: 'Which Google recognition model transcribes your calls.',
						examples: ['latest_long'],
						title: 'Speech model'
					})
				),
				enableAutomaticPunctuation: Type.Optional(
					Type.Boolean({
						description: 'Add punctuation to transcripts automatically.',
						title: 'Automatic punctuation'
					})
				)
			}),
			title: 'Google Cloud speech-to-text (buffered REST)',
			wiring: {
				code: 'googleSpeech({ apiKey: ${env.GOOGLE_SPEECH_API_KEY} ?? \'\', ...${settings} })',
				imports: [
					{ from: '@absolutejs/voice-google-speech', names: ['googleSpeech'] }
				]
			}
		})
	],
	settings: Type.Object({}),
	wiring: []
});
