/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { NeetsTTSOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Neets.ai text-to-speech adapter implementing `voice/tts` for `@absolutejs/voice` — budget-friendly streamed speech.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/neets",
    name: "@absolutejs/voice-neets",
    tagline: "Give your voice assistant a Neets.ai voice.",
  },
  implements: [
    defineImplementation<NeetsTTSOptions>()({
      contract: "voice/tts",
      factory: "neets",
      from: "@absolutejs/voice-neets",
      requires: {
        env: [
          {
            description: "Neets.ai API key",
            docsUrl: "https://neets.ai",
            key: "NEETS_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        voiceId: Type.String({
          description:
            "Voice id from the Neets.ai voice library that speaks the assistant’s replies.",
          title: "Voice",
        }),
        model: Type.Optional(
          Type.String({
            description: "Which Neets.ai model generates the speech.",
            examples: ["style-tts-2"],
            title: "Speech model",
          }),
        ),
      }),
      title: "Neets.ai text-to-speech",
      wiring: {
        code: "neets({ apiKey: ${env.NEETS_API_KEY} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-neets", names: ["neets"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
