/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { SonioxSTTOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Soniox real-time speech-to-text adapter implementing `voice/stt` for `@absolutejs/voice` — endpoint detection, language identification, and speaker diarization.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/soniox",
    name: "@absolutejs/voice-soniox",
    tagline: "Turn callers’ speech into text with Soniox.",
  },
  implements: [
    defineImplementation<SonioxSTTOptions>()({
      contract: "voice/stt",
      factory: "soniox",
      from: "@absolutejs/voice-soniox",
      requires: {
        env: [
          {
            description: "Soniox API key",
            docsUrl: "https://console.soniox.com",
            key: "SONIOX_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        model: Type.Optional(
          Type.String({
            description: "Which Soniox model transcribes your calls.",
            examples: ["stt-rt-preview"],
            title: "Speech model",
          }),
        ),
        enableLanguageIdentification: Type.Optional(
          Type.Boolean({
            description: "Detect which language each caller is speaking.",
            title: "Identify languages",
          }),
        ),
        enableSpeakerDiarization: Type.Optional(
          Type.Boolean({
            description:
              "Label which speaker said what when several people are on the call.",
            title: "Tell speakers apart",
          }),
        ),
      }),
      title: "Soniox speech-to-text",
      wiring: {
        code: "soniox({ apiKey: ${env.SONIOX_API_KEY} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-soniox", names: ["soniox"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
