/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from '@absolutejs/manifest';
import { Type } from '@sinclair/typebox';
import type { AzureSTTOptions, AzureTTSOptions } from './types';

export const manifest = defineManifest<Record<never, never>>()({
	contract: 1,
	identity: {
		category: 'voice',
		description:
			'Azure Speech adapters for `@absolutejs/voice`: `azureSTT` (real-time WebSocket recognition) implements `voice/stt` and `azureTTS` (neural voices over REST) implements `voice/tts`, both off one Azure Speech resource key.',
		docsUrl: 'https://github.com/absolutejs/voice-adapters/tree/main/azure',
		name: '@absolutejs/voice-azure',
		tagline: 'Hear callers and speak replies through Azure Speech.'
	},
	implements: [
		defineImplementation<AzureSTTOptions>()({
			contract: 'voice/stt',
			factory: 'azureSTT',
			from: '@absolutejs/voice-azure',
			requires: {
				env: [
					{
						description: 'Azure Speech resource key',
						docsUrl: 'https://portal.azure.com/#browse/Microsoft.CognitiveServices%2Faccounts',
						key: 'AZURE_SPEECH_KEY',
						secret: true
					}
				]
			},
			settings: Type.Object({
				region: Type.Optional(
					Type.String({
						description: 'Azure region your Speech resource lives in.',
						examples: ['eastus'],
						title: 'Azure region'
					})
				),
				language: Type.Optional(
					Type.String({
						description: 'Language callers are expected to speak.',
						examples: ['en-US'],
						title: 'Spoken language'
					})
				)
			}),
			title: 'Azure speech-to-text',
			wiring: {
				code: 'azureSTT({ subscriptionKey: ${env.AZURE_SPEECH_KEY} ?? \'\', ...${settings} })',
				imports: [
					{ from: '@absolutejs/voice-azure', names: ['azureSTT'] }
				]
			}
		}),
		defineImplementation<AzureTTSOptions>()({
			contract: 'voice/tts',
			factory: 'azureTTS',
			from: '@absolutejs/voice-azure',
			requires: {
				env: [
					{
						description: 'Azure Speech resource key',
						docsUrl: 'https://portal.azure.com/#browse/Microsoft.CognitiveServices%2Faccounts',
						key: 'AZURE_SPEECH_KEY',
						secret: true
					}
				]
			},
			settings: Type.Object({
				voice: Type.String({
					description:
						'Which Azure neural voice speaks the assistant’s replies.',
					examples: ['en-US-JennyNeural'],
					title: 'Voice'
				}),
				region: Type.Optional(
					Type.String({
						description: 'Azure region your Speech resource lives in.',
						examples: ['eastus'],
						title: 'Azure region'
					})
				),
				language: Type.Optional(
					Type.String({
						description: 'Language the assistant speaks.',
						examples: ['en-US'],
						title: 'Spoken language'
					})
				)
			}),
			title: 'Azure text-to-speech',
			wiring: {
				code: 'azureTTS({ subscriptionKey: ${env.AZURE_SPEECH_KEY} ?? \'\', ...${settings} })',
				imports: [
					{ from: '@absolutejs/voice-azure', names: ['azureTTS'] }
				]
			}
		})
	],
	settings: Type.Object({}),
	wiring: []
});
