/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from '@absolutejs/manifest';
import { Type } from '@sinclair/typebox';
import type { OpenAIRealtimeAdapterOptions } from './types';

export const manifest = defineManifest<Record<never, never>>()({
	contract: 1,
	identity: {
		category: 'voice',
		description:
			'OpenAI Realtime speech-to-speech adapter implementing `voice/realtime` for `@absolutejs/voice` — one model listens and talks over the official Realtime WebSocket API, replacing separate STT and TTS.',
		docsUrl: 'https://github.com/absolutejs/voice-adapters/tree/main/openai',
		name: '@absolutejs/voice-openai',
		tagline: 'Let one OpenAI model listen and talk on your calls.'
	},
	implements: [
		defineImplementation<OpenAIRealtimeAdapterOptions>()({
			contract: 'voice/realtime',
			factory: 'openai',
			from: '@absolutejs/voice-openai',
			requires: {
				env: [
					{
						description: 'OpenAI API key',
						docsUrl: 'https://platform.openai.com/api-keys',
						key: 'OPENAI_API_KEY',
						secret: true
					}
				]
			},
			settings: Type.Object({
				model: Type.Optional(
					Type.String({
						description: 'Which OpenAI Realtime model handles your calls.',
						examples: ['gpt-realtime-mini'],
						title: 'Model'
					})
				),
				voice: Type.Optional(
					Type.String({
						description: 'Which built-in OpenAI voice the assistant speaks with.',
						examples: ['marin'],
						title: 'Voice'
					})
				),
				instructions: Type.Optional(
					Type.String({
						description:
							'How the assistant should behave: its role, tone, and guardrails.',
						title: 'Assistant instructions'
					})
				)
			}),
			title: 'OpenAI Realtime speech-to-speech',
			wiring: {
				code: 'openai({ apiKey: ${env.OPENAI_API_KEY} ?? \'\', ...${settings} })',
				imports: [
					{ from: '@absolutejs/voice-openai', names: ['openai'] }
				]
			}
		})
	],
	settings: Type.Object({}),
	wiring: []
});
