/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from '@absolutejs/manifest';
import { Type } from '@sinclair/typebox';
import type { GeminiLiveAdapterOptions } from './types';

export const manifest = defineManifest<Record<never, never>>()({
	contract: 1,
	identity: {
		category: 'voice',
		description:
			'Gemini Live speech-to-speech adapter implementing `voice/realtime` for `@absolutejs/voice` — one Google model listens and talks in a single stream, replacing separate STT and TTS.',
		docsUrl: 'https://github.com/absolutejs/voice-adapters/tree/main/gemini',
		name: '@absolutejs/voice-gemini',
		tagline: 'Let one Gemini model listen and talk on your calls.'
	},
	implements: [
		defineImplementation<GeminiLiveAdapterOptions>()({
			contract: 'voice/realtime',
			factory: 'gemini',
			from: '@absolutejs/voice-gemini',
			requires: {
				env: [
					{
						description: 'Google AI Studio API key for Gemini',
						docsUrl: 'https://aistudio.google.com/apikey',
						key: 'GEMINI_API_KEY',
						secret: true
					}
				]
			},
			settings: Type.Object({
				model: Type.Optional(
					Type.String({
						description: 'Which Gemini Live model handles your calls.',
						examples: ['gemini-live-2.5-flash-preview'],
						title: 'Model'
					})
				),
				voiceName: Type.Optional(
					Type.String({
						description: 'Which built-in Gemini voice the assistant speaks with.',
						examples: ['Kore'],
						title: 'Voice'
					})
				),
				instructions: Type.Optional(
					Type.String({
						description:
							'How the assistant should behave: its role, tone, and guardrails.',
						title: 'Assistant instructions'
					})
				)
			}),
			title: 'Gemini Live speech-to-speech',
			wiring: {
				code: 'gemini({ apiKey: ${env.GEMINI_API_KEY} ?? \'\', ...${settings} })',
				imports: [
					{ from: '@absolutejs/voice-gemini', names: ['gemini'] }
				]
			}
		})
	],
	settings: Type.Object({}),
	wiring: []
});
