/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { PlayHTTTSOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "PlayHT text-to-speech adapter implementing `voice/tts` for `@absolutejs/voice` — streamed speech across the PlayHT voice engines.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/playht",
    name: "@absolutejs/voice-playht",
    tagline: "Give your voice assistant a natural PlayHT voice.",
  },
  implements: [
    defineImplementation<PlayHTTTSOptions>()({
      contract: "voice/tts",
      factory: "playht",
      from: "@absolutejs/voice-playht",
      requires: {
        env: [
          {
            description: "PlayHT API key",
            docsUrl: "https://play.ht/app/api-access",
            key: "PLAYHT_API_KEY",
            secret: true,
          },
          {
            description: "PlayHT user id (shown next to your API key)",
            docsUrl: "https://play.ht/app/api-access",
            key: "PLAYHT_USER_ID",
          },
        ],
      },
      settings: Type.Object({
        voice: Type.String({
          description:
            "Voice id or manifest URL from the PlayHT voice library that speaks the assistant’s replies.",
          title: "Voice",
        }),
        voiceEngine: Type.Optional(
          Type.String({
            description: "Which PlayHT voice engine generates the speech.",
            examples: ["Play3.0-mini"],
            title: "Voice engine",
          }),
        ),
      }),
      title: "PlayHT text-to-speech",
      wiring: {
        code: "playht({ apiKey: ${env.PLAYHT_API_KEY} ?? '', userId: ${env.PLAYHT_USER_ID} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-playht", names: ["playht"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
