/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { GladiaSTTOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Gladia real-time speech-to-text adapter implementing `voice/stt` for `@absolutejs/voice` — Solaria models with code-switching for multilingual callers.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/gladia",
    name: "@absolutejs/voice-gladia",
    tagline: "Turn callers’ speech into text with Gladia.",
  },
  implements: [
    defineImplementation<GladiaSTTOptions>()({
      contract: "voice/stt",
      factory: "gladia",
      from: "@absolutejs/voice-gladia",
      requires: {
        env: [
          {
            description: "Gladia API key",
            docsUrl: "https://app.gladia.io/account",
            key: "GLADIA_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        model: Type.Optional(
          Type.String({
            description: "Which Gladia model transcribes your calls.",
            examples: ["solaria-1"],
            title: "Speech model",
          }),
        ),
        codeSwitching: Type.Optional(
          Type.Boolean({
            description: "Follow callers who switch languages mid-sentence.",
            title: "Handle language switching",
          }),
        ),
      }),
      title: "Gladia speech-to-text",
      wiring: {
        code: "gladia({ apiKey: ${env.GLADIA_API_KEY} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-gladia", names: ["gladia"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
