/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { AssemblyAISTTOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "AssemblyAI real-time speech-to-text adapter implementing `voice/stt` for `@absolutejs/voice` — universal streaming models with vendor end-of-turn detection and key-term prompting.",
    docsUrl:
      "https://github.com/absolutejs/voice-adapters/tree/main/assemblyai",
    name: "@absolutejs/voice-assemblyai",
    tagline: "Turn callers’ speech into text with AssemblyAI.",
  },
  implements: [
    defineImplementation<AssemblyAISTTOptions>()({
      contract: "voice/stt",
      factory: "assemblyai",
      from: "@absolutejs/voice-assemblyai",
      requires: {
        env: [
          {
            description: "AssemblyAI API key",
            docsUrl: "https://www.assemblyai.com/app/api-keys",
            key: "ASSEMBLYAI_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        speechModel: Type.Optional(
          Type.String({
            description:
              "Which AssemblyAI streaming model transcribes your calls.",
            examples: ["universal-streaming-english", "u3-rt-pro"],
            title: "Speech model",
          }),
        ),
        formatTurns: Type.Optional(
          Type.Boolean({
            description:
              "Return neatly punctuated, formatted turns instead of raw words.",
            title: "Format turns",
          }),
        ),
      }),
      title: "AssemblyAI speech-to-text",
      wiring: {
        code: "assemblyai({ apiKey: ${env.ASSEMBLYAI_API_KEY} ?? '', ...${settings} })",
        imports: [
          { from: "@absolutejs/voice-assemblyai", names: ["assemblyai"] },
        ],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
