/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { SpeechmaticsSTTOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Speechmatics real-time speech-to-text adapter implementing `voice/stt` for `@absolutejs/voice` — accuracy-focused recognition with diarization and regional endpoints.",
    docsUrl:
      "https://github.com/absolutejs/voice-adapters/tree/main/speechmatics",
    name: "@absolutejs/voice-speechmatics",
    tagline: "Turn callers’ speech into text with Speechmatics.",
  },
  implements: [
    defineImplementation<SpeechmaticsSTTOptions>()({
      contract: "voice/stt",
      factory: "speechmatics",
      from: "@absolutejs/voice-speechmatics",
      requires: {
        env: [
          {
            description: "Speechmatics API key",
            docsUrl: "https://portal.speechmatics.com",
            key: "SPEECHMATICS_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        language: Type.Optional(
          Type.String({
            description: "Language callers are expected to speak.",
            examples: ["en"],
            title: "Spoken language",
          }),
        ),
        operatingPoint: Type.Optional(
          Type.Union([Type.Literal("enhanced"), Type.Literal("standard")], {
            description:
              "Enhanced is more accurate; standard is faster and cheaper.",
            title: "Accuracy mode",
          }),
        ),
        region: Type.Optional(
          Type.String({
            description: "Which Speechmatics region handles your audio.",
            examples: ["eu2"],
            title: "Region",
          }),
        ),
      }),
      title: "Speechmatics speech-to-text",
      wiring: {
        code: "speechmatics({ apiKey: ${env.SPEECHMATICS_API_KEY} ?? '', ...${settings} })",
        imports: [
          { from: "@absolutejs/voice-speechmatics", names: ["speechmatics"] },
        ],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
