/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { RimeTTSOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Rime text-to-speech adapter implementing `voice/tts` for `@absolutejs/voice` — fast conversational speech tuned for phone calls.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/rime",
    name: "@absolutejs/voice-rime",
    tagline: "Give your voice assistant a natural Rime voice.",
  },
  implements: [
    defineImplementation<RimeTTSOptions>()({
      contract: "voice/tts",
      factory: "rime",
      from: "@absolutejs/voice-rime",
      requires: {
        env: [
          {
            description: "Rime API key",
            docsUrl: "https://rime.ai",
            key: "RIME_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        speaker: Type.String({
          description:
            "Speaker from the Rime voice library that speaks the assistant’s replies.",
          examples: ["luna"],
          title: "Voice",
        }),
        modelId: Type.Optional(
          Type.String({
            description: "Which Rime model generates the speech.",
            examples: ["mistv2"],
            title: "Speech model",
          }),
        ),
        lang: Type.Optional(
          Type.String({
            description: "Language the assistant speaks.",
            examples: ["eng"],
            title: "Spoken language",
          }),
        ),
      }),
      title: "Rime text-to-speech",
      wiring: {
        code: "rime({ apiKey: ${env.RIME_API_KEY} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-rime", names: ["rime"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
