/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { CartesiaTTSOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Cartesia Sonic text-to-speech adapter implementing `voice/tts` for `@absolutejs/voice` — low-latency streamed audio over WebSocket or HTTP.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/cartesia",
    name: "@absolutejs/voice-cartesia",
    tagline: "Give your voice assistant a natural Cartesia voice.",
  },
  implements: [
    defineImplementation<CartesiaTTSOptions>()({
      contract: "voice/tts",
      factory: "cartesia",
      from: "@absolutejs/voice-cartesia",
      requires: {
        env: [
          {
            description: "Cartesia API key",
            docsUrl: "https://play.cartesia.ai/keys",
            key: "CARTESIA_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        voice: Type.String({
          description:
            "Voice id from the Cartesia voice library that speaks the assistant’s replies.",
          title: "Voice",
        }),
        model: Type.Optional(
          Type.String({
            description: "Which Sonic model generates the speech.",
            examples: ["sonic-2"],
            title: "Speech model",
          }),
        ),
        language: Type.Optional(
          Type.String({
            description: "Language the assistant speaks.",
            examples: ["en"],
            title: "Spoken language",
          }),
        ),
      }),
      title: "Cartesia text-to-speech",
      wiring: {
        code: "cartesia({ apiKey: ${env.CARTESIA_API_KEY} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-cartesia", names: ["cartesia"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
