/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { DeepgramConversationalOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "Deepgram real-time speech-to-text adapter implementing `voice/stt` for `@absolutejs/voice` — conversational Flux models with native end-of-turn detection, key terms, and keep-alive handling.",
    docsUrl: "https://github.com/absolutejs/voice-adapters/tree/main/deepgram",
    name: "@absolutejs/voice-deepgram",
    tagline: "Turn callers’ speech into text with Deepgram.",
  },
  implements: [
    defineImplementation<DeepgramConversationalOptions>()({
      contract: "voice/stt",
      factory: "deepgram",
      from: "@absolutejs/voice-deepgram",
      requires: {
        env: [
          {
            description: "Deepgram API key",
            docsUrl: "https://console.deepgram.com",
            key: "DEEPGRAM_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        model: Type.Union(
          [
            Type.Literal("flux"),
            Type.Literal("flux-general-en"),
            Type.Literal("flux-general-multi"),
          ],
          {
            default: "flux-general-en",
            description:
              "Which conversational Flux model transcribes your calls. Multi handles more languages.",
            title: "Speech model",
          },
        ),
        language: Type.Optional(
          Type.String({
            description: "Language callers are expected to speak.",
            examples: ["en"],
            title: "Spoken language",
          }),
        ),
      }),
      title: "Deepgram speech-to-text (Flux)",
      wiring: {
        code: "deepgram({ apiKey: ${env.DEEPGRAM_API_KEY} ?? '', ...${settings} })",
        imports: [{ from: "@absolutejs/voice-deepgram", names: ["deepgram"] }],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
