/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { ElevenLabsTTSOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "ElevenLabs text-to-speech adapter implementing `voice/tts` for `@absolutejs/voice` — streamed low-latency audio over WebSocket or HTTP with the full voice library.",
    docsUrl:
      "https://github.com/absolutejs/voice-adapters/tree/main/elevenlabs",
    name: "@absolutejs/voice-elevenlabs",
    tagline: "Give your voice assistant a natural ElevenLabs voice.",
  },
  implements: [
    defineImplementation<ElevenLabsTTSOptions>()({
      contract: "voice/tts",
      factory: "elevenlabs",
      from: "@absolutejs/voice-elevenlabs",
      requires: {
        env: [
          {
            description: "ElevenLabs API key",
            docsUrl: "https://elevenlabs.io/app/settings/api-keys",
            key: "ELEVENLABS_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        voiceId: Type.String({
          description:
            "Voice id from your ElevenLabs voice library that speaks the assistant’s replies.",
          examples: ["21m00Tcm4TlvDq8ikWAM"],
          title: "Voice",
        }),
        modelId: Type.Optional(
          Type.String({
            description:
              "Which ElevenLabs model generates the speech. Flash is fastest for live calls.",
            examples: ["eleven_flash_v2_5"],
            title: "Speech model",
          }),
        ),
      }),
      title: "ElevenLabs text-to-speech",
      wiring: {
        code: "elevenlabs({ apiKey: ${env.ELEVENLABS_API_KEY} ?? '', ...${settings} })",
        imports: [
          { from: "@absolutejs/voice-elevenlabs", names: ["elevenlabs"] },
        ],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
