/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from "@absolutejs/manifest";
import { Type } from "@sinclair/typebox";
import type { OpenAIWhisperSTTOptions } from "./types";

export const manifest = defineManifest<Record<never, never>>()({
  contract: 2,
  identity: {
    category: "voice",
    description:
      "OpenAI Whisper / gpt-4o-transcribe buffered speech-to-text adapter implementing `voice/stt` for `@absolutejs/voice` — accumulates audio per turn and transcribes on flush, a simple low-cost lane for post-turn transcripts.",
    docsUrl:
      "https://github.com/absolutejs/voice-adapters/tree/main/openai-whisper",
    name: "@absolutejs/voice-openai-whisper",
    tagline: "Turn callers’ speech into text with OpenAI Whisper.",
  },
  implements: [
    defineImplementation<OpenAIWhisperSTTOptions>()({
      contract: "voice/stt",
      factory: "openaiWhisper",
      from: "@absolutejs/voice-openai-whisper",
      requires: {
        env: [
          {
            description: "OpenAI API key",
            docsUrl: "https://platform.openai.com/api-keys",
            key: "OPENAI_API_KEY",
            secret: true,
          },
        ],
      },
      settings: Type.Object({
        model: Type.Optional(
          Type.String({
            description:
              "Which OpenAI transcription model transcribes your calls.",
            examples: ["gpt-4o-mini-transcribe"],
            title: "Speech model",
          }),
        ),
        language: Type.Optional(
          Type.String({
            description: "Language callers are expected to speak.",
            examples: ["en"],
            title: "Spoken language",
          }),
        ),
      }),
      title: "OpenAI Whisper speech-to-text (buffered)",
      wiring: {
        code: "openaiWhisper({ apiKey: ${env.OPENAI_API_KEY} ?? '', ...${settings} })",
        imports: [
          {
            from: "@absolutejs/voice-openai-whisper",
            names: ["openaiWhisper"],
          },
        ],
      },
    }),
  ],
  settings: Type.Object({}),
  wiring: [],
});
