/* GENERATED by scripts/generate-manifests.ts — edit the vendor table there
 * and re-run `bun scripts/generate-manifests.ts`. The options-type imports keep
 * each settings schema drift-checked against this package's real config type. */
import { defineImplementation, defineManifest } from '@absolutejs/manifest';
import { Type } from '@sinclair/typebox';
import type { LMNTTTSOptions } from './types';

export const manifest = defineManifest<Record<never, never>>()({
	contract: 1,
	identity: {
		category: 'voice',
		description:
			'LMNT text-to-speech adapter implementing `voice/tts` for `@absolutejs/voice` — streamed low-latency speech with conversational styling.',
		docsUrl: 'https://github.com/absolutejs/voice-adapters/tree/main/lmnt',
		name: '@absolutejs/voice-lmnt',
		tagline: 'Give your voice assistant a natural LMNT voice.'
	},
	implements: [
		defineImplementation<LMNTTTSOptions>()({
			contract: 'voice/tts',
			factory: 'lmnt',
			from: '@absolutejs/voice-lmnt',
			requires: {
				env: [
					{
						description: 'LMNT API key',
						docsUrl: 'https://app.lmnt.com/account',
						key: 'LMNT_API_KEY',
						secret: true
					}
				]
			},
			settings: Type.Object({
				voice: Type.String({
					description:
						'Voice id from the LMNT voice library that speaks the assistant’s replies.',
					examples: ['lily'],
					title: 'Voice'
				}),
				model: Type.Optional(
					Type.String({
						description: 'Which LMNT model generates the speech.',
						examples: ['blizzard'],
						title: 'Speech model'
					})
				),
				language: Type.Optional(
					Type.String({
						description: 'Language the assistant speaks.',
						examples: ['en'],
						title: 'Spoken language'
					})
				)
			}),
			title: 'LMNT text-to-speech',
			wiring: {
				code: 'lmnt({ apiKey: ${env.LMNT_API_KEY} ?? \'\', ...${settings} })',
				imports: [
					{ from: '@absolutejs/voice-lmnt', names: ['lmnt'] }
				]
			}
		})
	],
	settings: Type.Object({}),
	wiring: []
});
